#!/bin/sh

#This script try to download all youtube videos from any channel
#Recommend: put this script in empty folder before run!!!!
#Requiriments: yt-dlp;jq;ffmpeg;tr
#Usage: script.sh YOUTUBE_CHANNEL_URL [FOLDER_NAME]
#NOTE: The attribute FOLDER_NAME is optional. Use if you want to backup multiple_channels at once
#Tested on ubuntulinux based systems

####VARIABLES####

#CHANNEL_URL
URL_CHANNEL="$1"
FOLDER="$2"

#OUTPUT_FOLDER
 if [ -z "$2" ]; then
        FOLDER=output
    fi

mkdir ${FOLDER}
cd ${FOLDER}

#TEMPORARY FILE
VIDEO_LIST_CSV=list.csv

#OUTPUT FORMAT like mp3,mp4,aac etc. See yt-dlp docummentation for details
OUTPUT_FORMAT=aac

#Set your navigator for cookies. Useful for download restricted/member videos. EG:firefox,chrome etc
NAVIGATOR=firefox

#Generating video CSV URL
yt-dlp -j --flat-playlist ${URL_CHANNEL} | jq -r '[.url] | @csv' > ${VIDEO_LIST_CSV}

#Removing all quotes from CSV file
tr -d \" < ${VIDEO_LIST_CSV} > ${VIDEO_LIST_CSV}_tmp
rm ${VIDEO_LIST_CSV}
mv ${VIDEO_LIST_CSV}_tmp ${VIDEO_LIST_CSV}

#Downloading videos
yt-dlp --cookies-from-browser ${NAVIGATOR} -a ${VIDEO_LIST_CSV} -t ${OUTPUT_FORMAT} -o "%(upload_date>%Y)s/%(upload_date>%m)s/%(upload_date>%d)s/%(upload_date>%Y-%m-%d)s_%(epoch-3600>%H-%M-%S)s_%(title)s" --sleep-requests 1
#yt-dlp --cookies-from-browser ${NAVIGATOR} -a ${VIDEO_LIST_CSV} -t ${OUTPUT_FORMAT} -o "%(upload_date>%Y-%m-%d)s_%(epoch-3600>%H-%M-%S)s_%(title)s" --sleep-requests 1

#Removing temporary file list
rm ${VIDEO_LIST_CSV}

